### ISSUE TITLE
MHC region filtering does not filter MHC region

### ISSUE THREAD

**Issue by Lipastomies** [FINNGEN/finemapping-pipeline#36]
The preprocessing script (make_finemap_inputs.py) includes a flag to filter out the MHC region from possible credible set regions. However, it only filters out lead variants. If a lead variant is right on the edge of the MHC region ( e.g. 34.1MB), then the window to finemap extends up to half the window to MHC region, so the MHC region effectively gets finemapped.

Is this intended behaviour? In some autoimmune-related phenotypes, about half of the credible sets can have their causal variant/causal variants with largest PIP in the excluded region, so this does pollute the finemapping results somewhat.

If it is not, one solution would be to clamp the regions so that given an MHC region chr6:25e6-34e6 and a possible finemappable region chr6:33e6-36e6 (from lead variant in chr6:34.5e6) the resulting region would be chr6:34e6-36e6.

**Comment by Lipastomies** [comment]
@Fedja @mkanai what do you think?

**Comment by mkanai** [comment]
Great catch @Lipastomies. This is not intended and indeed we removed the flag in UKBB/BBJ fine-mapping after recognizing this issue. Instead, we're currently removing the region containing MHC post-hoc after the preprocessing process. I will fix this and make an PR soon.

**Comment by mkanai** [comment]
resolved in #45
