### ISSUE TITLE
How to handle genetic variation missing values in susieR analysis?

### ISSUE THREAD

**Issue by Shicheng-Guo** [FINNGEN/finemapping-pipeline#39]
How FinnGen analytic group to handle genetic variation missing values in susieR analysis? 

Thanks.

Shicheng

**Comment by mkanai** [comment]
Hi Shicheng,

We used imputed genotype data. When you have missing genotypes from e.g. sequencing studies, you can either simply mean-impute them or use more sophisticated algorithms.
