### ISSUE TITLE
task ldstore_finemap.combine can fail silently on e.g. out of disk 

### ISSUE THREAD

**Issue by Lipastomies** [FINNGEN/finemapping-pipeline#53]
The combine task does not terminate on return codes other than 0, so it can fail silently, causing trouble for the summarization step.

This happened in e.g the following task: gs://CROMWELL_BUCKET_FGREF/finemap/31a56270-b625-44d5-92d5-2a015657fc06/call-ldstore_finemap/shard-0/sub.ldstore_finemap/c20db631-6e47-4203-8d88-398e98e5d213/call-combine/

**Comment by mkanai** [comment]
Good catch @Lipastomies -- is there any way to trap the out of space error? Alternatively, we can make a small `_SUCCESS`  file at the very end to confirm successful finish

**Comment by Lipastomies** [comment]
I think just adding a "set -eux" in the beginning should work. Most likely something will fail on out of disk, so that should catch it.

**Comment by mkanai** [comment]
ah because cromwell only checks whether the outputs exist... cool, would mind making a PR? thanks!

**Comment by Lipastomies** [comment]
yeah, can do

**Comment by Lipastomies** [comment]
PR in #54
