### ISSUE TITLE
write make_finemap_inputs.py in python3

### ISSUE THREAD

**Issue by Fedja** [FINNGEN/finemapping-pipeline#64]
docker building does not work. 
this one script is written in python2 and pybedtools at least seemed to fail in building to python2. 

Could figure out to build to py2 but probably would make sense to upgrad. Seems some pandas functions at least work differently. need to carefully verify the upgrade gets correct output.

**Comment by mkanai** [comment]
will make a PR -- I have something already

**Comment by Fedja** [comment]
great was just doing this myself :)  will wait for pr
it was tuple unpacking instead of pandas at this point
